recipeSrcMapping:
    hellow-world-recipe: src

# Manually set bundle file name for 3rd-party libaraies, otherwise browserify
# will bundle them with every package that depends on them.
vendorBundleMap:
  core: # bundle name
      - lodash
      - jquery
      - bluebird

browserifyNoParse:
    - q
    - lodash
    - jquery
    - @dr/gsap
    - @dr/angularjs
# Recipes which are installed from registry server, they are owned by other contributors,
# add to this list to make them a part of you server.
#
# You need to manually run commands to make sure them downloaded.
#  npm install @dr/garage-recipe
#  npm install @dr/examples-recipe
# And maybe specify a version number like `npm install @dr/garage-recipe@0.0.0`
installedRecipes:
    - node_modules/@dr/*-recipe
    - node_modules/@dr/recipe-*

port: 14334
